### ISSUE TITLE
Internal Digest implementation doesn't work with ONVIF Foscam/amcrest IPCAM

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/device-camera-go#104]
Need to refactor Digest code to use standard module rather than internal implementation
Changing code to use `github.com/xinsnake/go-http-digest-auth-client`, rather than own internal implementation resolved issue. This module is a possible replacement for the internal code.

**Comment by tonyespy** [comment]
I have an SV3C camera which also is refusing to accept basic or digest authentication from device-camera, so maybe this is more serious than we think?

Also FYI, the maintainer of the suggested alternative has added the following to the repository:

> Due to time limit on my side I won't be able to maintain this package. Please consider using some other library like https://github.com/rkl-/digest. Thanks for your support!

**Comment by tonyespy** [comment]
Unfortunately, updating to `github.com/xinsnake/go-http-digest-auth-client `didn't fix the problem with my camera...  That said, it's a trivial update. I'll cleanup and attach a patch when I get a chance.

**Comment by jpwhitemn** [comment]
As @tonyespy indicated, the library suggested (github.com/xinsnake/go-http-digest-auth-client) may be an issue.  It is already in archive status by the owner.  So it will not be updated.  As he also suggested, the owner suggests using:  https://github.com/rkl-/digest

But this library is also not very well maintained (last updated 4 years ago) and has no additional developers, only 3 watchers and 3 stars.  Under any other circumstance, we would probably not authorize either package for use in EdgeX.

IOTech is working to create a new DS for cameras and ONVIF.  The timing of this won't be done for Jakarta and it is a little unclear as to whether we would open source all of it or not (as it is work for a client).  But before we do too much work to fix this bug, allow IOTech to progress with its work.  We are planning to use a completely different Go library than the one used currently.  This will solve the issue with digest code is unclear.  But at the very least, IOTech can share the experience with the new Go library and provide information on a work around on the digest code issue even if the service itself is not made open source.

**Comment by bnevis-i** [comment]
@jpwhitemn It looks like both of these libraries, excluding tests, are less than 400 LOC.  Perhaps we could just write our own inline implementation and not take such a small dependency?

**Comment by jpwhitemn** [comment]
Possibly @bnevis-i - also wondering if the new library we are using has incorporated a sub library (or their own code) to deal with this as well.  That is why I am advocating placing this issue on hold until we have more info.  It may OBE.

**Comment by lenny-intel** [comment]
@jpwhitemn , @bnevis-i , for Jakarta we could just pick one of these and pull it into our repo rather than write our own.

**Comment by bnevis-i** [comment]
Please refer to https://github.com/edgexfoundry/device-onvif-camera which replaces this service.
