### ISSUE TITLE
Secrets retry loop impacts device callbacks

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-camera-go#139]
# 🐞 Bug Report

### Description and Minimal Reproduction
Install the Ireland version of EdgeX, and any service which requires secrets to be provisioned before it can be used (e.g. device-camera when one of the static devices requires a username/password). If the service can't find it's secrets in Vault, there's a retry loop which eventually fails out (configurable).  This gives developers (or maybe some application on the EdgeX system) time to call the device service's /secret endpoint to inject the secrets before the retry loop expires.

The few times I've done this (while testing device-camera), I kept seeing this error messge logged:

`level=ERROR ts=2021-08-26T23:58:47.109870081Z app=core-metadata source=notify.go:43 msg="fail to invoke device service callback for adding device Camera001, err: failed to send a http request -> Post \"http://localhost:59985/api/v2/callback/device\": EOF"`

Note, a single camera device has been provisioned, so the device service adds it to Core Metadata, maybe the secrets loop happens before all the mux router has been fully setup?

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**EdgeX Version:** 2.0.0
**Device Camera:** 2.0.0

*Note* - I reproduced with the latest snaps from the 2.0 track (e.g. use `--channel=2.0` when installing the snaps).

**Anything else relevant?**

**Comment by iain-anderson** [comment]
closing this: device-onvif-camera is released in v2.3 and replaces this service
