### ISSUE TITLE
Configurate the Hikvision camera, got error: camera is not available at http://xxx.xxx.xxx.xxx/onvif/Media or it does not support ONVIF services

### ISSUE THREAD

**Issue by watjt** [edgexfoundry/device-camera-go#163]
This is /res/devices/camera.toml configuration:
[[DeviceList]]
Name = "Camera-hikvision"
ProfileName = "camera"
Description = "My test camera"
  [DeviceList.Protocols]
    [DeviceList.Protocols.HTTP]
    Address = "my Hikvision ip"
    AuthMethod = "usernamepassword"
    CredentialsPath = "credentials001"
[[DeviceList.AutoEvents]]
    Interval   = "30s"
    OnChange   = false
    SourceName = "OnvifSnapshot"

How should I configurate it?

**Comment by MonicaisHer** [comment]
Try this:
Address = "my Hikvision ip: Camera-hikvision's default ONVIF port"

**Comment by watjt** [comment]
The user name /password can be parsed from "CredentialsPath", but I don't know data format. have a example for reference? I'm not write any data to this file.

**Comment by MonicaisHer** [comment]
```
curl -w %{http_code} -X POST \
-d '{
  "apiVersion": "2",
  "path" : "credentials001",
  "secretData" : [
    {
      "key" : "username",
      "value" : "admin"
    },
	{
      "key" : "password",
      "value" : "admin"
    }
  ]
}' http://localhost:59985/api/v2/secret
```

**Comment by watjt** [comment]
We need add usename/password(InsecureSecrets) for https://github.com/edgexfoundry/device-camera-go/blob/927839543b56d0b3b1483c918eb68a660d8b6c21/cmd/res/configuration.toml#L12 , Now it's work.
