### ISSUE TITLE
When add an new autoevent, not trigger it  , need restart device service to trigger it

### ISSUE THREAD

**Issue by edgego** [edgexfoundry/device-camera-go#171]
tested version 2.1.0, when add an new autoevent or change an autoevent, found  not take the changes effect . But when restart device service then the changes are effected.
   Checked the code, found the callback : func (d *Driver) AddDevice(deviceName string, protocols map[string]models.ProtocolProperties, adminState models.AdminState) or func (d *Driver) UpdateDevice(deviceName string, protocols map[string]models.ProtocolProperties, adminState models.AdminState)  not be called.

**Comment by cloudxxx8** [comment]
if the callback is not called, please check whether your core-metadata and device-camera is in the same network.
are you running core services in docker and running device-camera in IDE?  if yes, please modify the service host of device-camera to the docker0 ip address, such as 172.17.0.1

**Comment by edgego** [comment]
@cloudxxx8   Thanks for you reply, core-metadata and device-camera are in same network. Both core-metadata and device-camera are running with kubernetes .  Also tested device-mobus(2.1.0） within same kubernetes cluster,device-modbus is ok.

**Comment by edgego** [comment]
close this issue, fixed my configuration .
