### ISSUE TITLE
Usb Web Cam Usage

### ISSUE THREAD

**Issue by erdicaliskanew** [edgexfoundry/device-camera-go#175]
Dear All,

I am trying to get a surveillance video in office. For this I am using "Logitech bcc950" web cam which is non ONVIF-compliant.
So, is it possible to video streaming over device-camera-go service with usb web cam ("Logitech bcc950") on EdgeX?

Note: The Jakarta version EdgeX is used.

**Comment by cloudxxx8** [comment]
we are developing the usb camera device service, and it is under review
https://github.com/edgexfoundry-holding/device-usb-camera
you can make a try
