### ISSUE TITLE
how do multiple cameras be attached to this microservice

### ISSUE THREAD

**Issue by wangmingjunabc** [edgexfoundry/device-camera-go#29]
when I use this DS， the camera configuration info is written to the file in  res/configuration.toml and configuration-driver.toml.   If the DS is running， how can I add new camera to be controlled by this DS dynamically,but not to configure  the .toml file。Thanks for any help!

**Comment by cloudxxx8** [comment]
FYI
You can connect to Consul (http://localhost:8500) and modify the configuration in key/value store.
https://docs.edgexfoundry.org/1.2/microservices/configuration/Ch-Configuration/
