### ISSUE TITLE
Upgrade to the latest SDK

### ISSUE THREAD

**Issue by hahattan** [edgexfoundry/device-camera-go#30]
Upgrade to the latest SDK, and apply the appropriate changes

- use go-mod-bootstrap
- remove configuration in docker folder
- deprecate logging service
- modify Dockerfile
- add mediaType into binary profile

**Comment by hahattan** [comment]
@weichou1229 could you help upgrade your PR's SDK version to v1.2.0 when you're free? thanks

**Comment by weichou1229** [comment]
No problem, done.

**Comment by hahattan** [comment]
there's a API change you need to update for the protocolDriver.Initialize function, FYI:
https://github.com/edgexfoundry/device-rest-go/pull/20/files#diff-db7f18446e5168af209b17253094f5c2R35

**Comment by weichou1229** [comment]
Thanks! Updated.
