### ISSUE TITLE
configuration.toml does not support unique username/password settings when using multiple cameras 

### ISSUE THREAD

**Issue by siggiskulason** [edgexfoundry/device-camera-go#45]
The configuration file for camera-go sets the username/password for onvif cameras globally for the driver. That means that if we have more than one camera, each camera will be initialized with the same username/password settings.

It should be possible to configure unique initial username/password configurations for each camera.

https://github.com/edgexfoundry/device-camera-go/blob/c8688c583b3eeb3ad107f14a47c5424615149cea/cmd/res/configuration.toml#L76-L85

If we have a configuration file with more than one  physical camera defined:
```
[[DeviceList]]
  Name = 'Camera001'
  Profile = 'camera'
  Description = 'Back garden camera'
  Location = 'back garden'
  [DeviceList.Protocols]
    [DeviceList.Protocols.HTTP]
      Address = '192.168.1.103:8080'

[[DeviceList]]
  Name = 'Camera002'
  Profile = 'camera'
  Description = 'Front garden camera'
  Location = 'front garden'
  [DeviceList.Protocols]
    [DeviceList.Protocols.HTTP]
      Address = '192.168.1.104:8080'
```
Then the problem is if those physical camera devices need different username/password settings. When the configuration file is processed, the username/password is read from the driver configuration:
https://github.com/edgexfoundry/device-camera-go/blob/c8688c583b3eeb3ad107f14a47c5424615149cea/internal/driver/config.go#L24-L44

 and then applied to each camera:
https://github.com/edgexfoundry/device-camera-go/blob/c8688c583b3eeb3ad107f14a47c5424615149cea/internal/driver/driver.go#L377-L395

**Comment by lenny-intel** [comment]
@siggiskulason , do you agree this has been resolved now with https://github.com/edgexfoundry/device-camera-go/pull/98? If so, please close this issue after linking it to that PR, THX!

**Comment by siggiskulason** [comment]
Fixed in https://github.com/edgexfoundry/device-camera-go/pull/98
