### ISSUE TITLE
Security credentials should come from Vault, not configuration.toml

### ISSUE THREAD

**Issue by siggiskulason** [edgexfoundry/device-camera-go#46]
Specifying usernames/passwords in general in the device-camera configuration.toml file  is non-compliant usage per the [Secrets Distribution ADR](https://github.com/edgexfoundry/edgex-docs/pull/141). The code should be updated to retrieve passwords from Vault. 

See also issues
[configuration.toml does not support unique username/password settings when using multiple cameras #45](https://github.com/edgexfoundry/device-camera-go/issues/45)

[Provide internal API to retrieve credentials from a secret store #564](https://github.com/edgexfoundry/device-sdk-go/issues/564)

**Comment by lenny-intel** [comment]
Implementation should follow pattern done for Device MQTT here:
https://github.com/edgexfoundry/device-mqtt-go/pull/197

**Comment by siggiskulason** [comment]
@lenny-intel / @iain-anderson - I'll pick up this issue and create a PR for it.

**Comment by lenny-intel** [comment]
@siggiskulason,  @jim-wang-intel has already been reviewing how to do this once the service is updated for V2.  Please work with him.

**Comment by siggiskulason** [comment]
@jim-wang-intel - great that you're working on this. I haven't done any work on this yet, but happy to be of assistance. I'll contact you on slack
